### ISSUE TITLE
数据格式是什么样的

### ISSUE THREAD

**Issue by ZChaowen** [thuml/OpenLTM#1]
能否提供一个UTSD-npy的样例数据和模型的checkpoints

**Comment by WenWeiTHU** [comment]
Hi, you can refer to this [repo](https://github.com/thuml/Large-Time-Series-Model)!

**Comment by ZChaowen** [comment]
什么时候能支持_A Decoder-Only Foundation Model for Time-Series Forecasting_

**Comment by WenWeiTHU** [comment]
目前您可以移步TimesFM官方仓库：https://github.com/google-research/timesfm/

**Comment by ZChaowen** [comment]
模型的Pre-training使用的是单变量数据吗？我看代码中UTSD_Npy的数据获取还是单变量的。
