### ISSUE TITLE
is UTSD in numpy format UTSD-12G?

### ISSUE THREAD

**Issue by hwseo95** [thuml/OpenLTM#12]
as the title states, is UTSD in numpy format UTSD-12G?
if so, how do I get the subset of UTSD-12G from numpy-format UTSD?

**Comment by WenWeiTHU** [comment]
Thanks for your interest. There are two versions of UTSD (both of them are exactly UTSD-12G): [[HuggingFace]](https://huggingface.co/datasets/thuml/UTSD), [[Numpy]](https://cloud.tsinghua.edu.cn/f/93868e3a9fb144fe9719/). If you are interested in a specific subset, we recommend you use the HuggingFace version :)
