### ISSUE TITLE
LLMs for timeseries

### ISSUE THREAD

**Issue by khairulislam** [thuml/OpenLTM#15]
Do you plan on including the LLMs for time-series models here? e.g. CALF, GPT4TS.

**Comment by WenWeiTHU** [comment]
Of course. Thanks for the good work you mentioned, we will continue to add these models. Also welcome any PR 👏

**Comment by khairulislam** [comment]
Great, I can create pull requests for some of them.

**Comment by WenWeiTHU** [comment]
@khairulislam 

Cool! Thanks so much for your excellent work.
