### ISSUE TITLE
Request for Pre-trained Model Download Link

### ISSUE THREAD

**Issue by qixuxiang** [thuml/OpenLTM#2]
I'm thrilled to see this outstanding work! However, I couldn't find the download link for the pre-trained model (.pth file) in the README section. It would be greatly appreciated if you could provide the link for the pre-trained model.

**Comment by WenWeiTHU** [comment]
Hello! Thank you for your interest. At an initial stage, this repository is not intended to provide model checkpoints but to provide the implementation of pre-training/adaptation pipeline, to explore the large model design in the time series field. For the checkpoint of large time-series models, you can refer to their official repositories such as [Timer](https://github.com/thuml/Large-Time-Series-Model), [TimesFM](https://github.com/google-research/timesfm/), [Moirai](https://github.com/SalesforceAIResearch/uni2ts).

**Comment by qixuxiang** [comment]
Thank you for your prompt response and for clarifying the purpose of the repository. I appreciate the effort put into providing the implementation of the pre-training/adaptation pipeline and exploring large model designs in the time series field.
I look forward to the continued development of this repository and hope that the pre-trained model for Timer-XL will be made available in the future. This would greatly facilitate fine-tuning and usage of the model.

**Comment by WenWeiTHU** [comment]
Thanks. We will also release the relevant checkpoints of Timer-XL in this [repo](https://github.com/thuml/Timer-XL). Please stay tuned!
---- Replied Message ----
***@***.***>Date10/21/2024 12:53 ***@***.***> CcYong ***@***.***>,
***@***.***>SubjectRe: [thuml/OpenLTM] Request for Pre-trained Model Download Link (Issue #2)
Thank you for your prompt response and for clarifying the purpose of the repository. I appreciate the effort put into providing the implementation of the pre-training/adaptation pipeline and exploring large model designs in the time series field.
I look forward to the continued development of this repository and hope that the pre-trained model for Timer-XL will be made available in the future. This would greatly facilitate fine-tuning and usage of the model.
