### ISSUE TITLE
Pre-training

### ISSUE THREAD

**Issue by ZChaowen** [thuml/OpenLTM#3]
模型的Pre-training使用的是单变量数据吗？我看代码中UTSD_Npy的数据获取是单变量的。

**Comment by Levi-Ackman** [comment]
一般*TimeLLM*都是单变量预训练的，然后想预测多变量的时候使用*channel-independent*来重复预测**N**个目标变量的值

**Comment by ZChaowen** [comment]
@Levi-Ackman 那用基于Timer-XL训练的大模型，进行zero-shot依旧仅支持单变量输入了。

**Comment by hvlgo** [comment]
Timer-XL supports multivariable pre-training. We plan to train it on large-scale multivariable dataset, so stay tuned!
