### ISSUE TITLE
Classification and Pre-trained Weights

### ISSUE THREAD

**Issue by ooooooover** [thuml/OpenLTM#4]
Thank you for your outstanding contributions! I would like to know if modifying the final head layer would be sufficient to adapt the model to a classification task, and whether there are any plans to provide pre-trained weights for the model on large-scale datasets.

**Comment by WenWeiTHU** [comment]
Hi, please refer to [this repo](https://github.com/thuml/Large-Time-Series-Model) for the pre-trained checkpoint

**Comment by jexterliangsufe** [comment]
Hi, There are only checkpoints for Timer but not Timer-XL in the link above. Will you release Timer-XL checkpoints?

**Comment by WenWeiTHU** [comment]
Of course, we will release the checkpoint of Timer-XL. Please stay tuned.
