### ISSUE TITLE
Pre-trained model weights and gpu requirements

### ISSUE THREAD

**Issue by jexterliangsufe** [thuml/OpenLTM#5]
Great works! 
I have two questions about Timer-XL. 
1. Will you open source the model weights which achieved the best performance in the paper? 
2. I noticed the gpu you used is "NVIDIA A100 Tensor Core GPUs" in the paper. What are the minimum GPU requirements for pre-training this model? Is a single V100 sufficient?

**Comment by ZChaowen** [comment]
batch_size设小一点其实不用那么多gpu资源

**Comment by WenWeiTHU** [comment]
关于计算资源需求：在UTSD上预训练是在4张A100 40G上进行的（对应预训练规模大概是1B时间点训一天左右），如果是微调或者Superwised Training，用一张4090应该就够了

**Comment by Leopold2333** [comment]
> 关于计算资源需求：在UTSD上预训练是在4张A100 40G上进行的（对应预训练规模大概是1B时间点训一天左右），如果是微调或者Superwised Training，用一张4090应该就够了。当然也可以根据GPU配置适当修改batch size。

想问下，有没有使用这个仓库里的moirai预训练的参数呢？moirai原文的仓库里的预训练参数没法直接迁移过来昂

**Comment by ooooooover** [comment]
The Moirai implementation in this repository is not the official one, so it cannot utilize the official pre-trained weights. It would be great if the Moirai weights could be shared.

**Comment by WenWeiTHU** [comment]
Since it is very difficult to unify the training framework, we have omitted some specific designs of the models. We have added this note :)

<img width="830" alt="image" src="https://github.com/user-attachments/assets/d2880ead-03fd-4292-9692-8340f60f10ff">
