### ISSUE TITLE
questions about MOIRAI implementation

### ISSUE THREAD

**Issue by Sunwang-git** [thuml/OpenLTM#7]
I noticed that the official implementation of moirai(or uni2ts) uses mixture distribution as the model output, but in this implementation I don't see the similar part. I am not sure if the code was wrong or I was my wrong. 
again, I want to thank the author group for their contribution!

**Comment by WenWeiTHU** [comment]
Since it is very difficult to unify the training framework, we have omitted some specific designs of the models. We added this note :)

<img width="829" alt="image" src="https://github.com/user-attachments/assets/808af9c0-76aa-47b6-b8a7-ca70717c49f2">
